### ISSUE TITLE
Impossible to inject Config

### ISSUE THREAD

**Issue by ptondereau** [GrahamCampbell/Laravel-TestBench#14]
Hello and thank you for this awesome package.

I don't know if it is an issue or it's me but when I test my ServiceProvider with the method assertIsInjectabl($name) and in the register method, I do: 
```
$this->app->singleton('excel-importer.importer', function (Container $app) {
    $config = $app->config->get('excel-importer'); // return null :'( but $app->config is OK
    return new Importer($config);
});
```

It throws this exception:
```
The class 'Me\ExcelImporter\Importer' couldn't be automatically injected. Unresolvable dependency resolving [Parameter #0 [ <required> array $config ]] in class Me\ExcelImporter\Importer
Failed asserting that false is true.
```

Boot method of my service provider:
```
$source = realpath(__DIR__ . '/../config/excel-importer.php'); // Path is OK
$this->publishes([$source => config_path('excel-importer.php')]);
$this->mergeConfigFrom($source, 'excel-importer');
```

Many thanks

**Comment by vinkla** [comment]
Please share your `Importer` class.

**Comment by ptondereau** [comment]
@vinkla https://gist.github.com/ptondereau/47f17bb1178ddb67e1c7119ec30751fc

**Comment by GrahamCampbell** [comment]
This is unrelated to my code, and would fail anyway.

**Comment by GrahamCampbell** [comment]
You forgot to simply alias that binding to the class.

**Comment by GrahamCampbell** [comment]
After calling app->singleton, put this afterwards:

```php
$this->app->alias('excel-importer.importer', Importer::class);
```

**Comment by GrahamCampbell** [comment]
Without that code, laravel won't know what to inject.

**Comment by ptondereau** [comment]
@GrahamCampbell many thanks, and sorry for this annoying issue
