### ISSUE TITLE
[Feature Request] PHPUnit 6.0 support

### ISSUE THREAD

**Issue by vinkla** [GrahamCampbell/Laravel-TestBench#16]
Is there a way we could support all three versions (^4.8, ^5.0 and ^6.0) of PHPUnit in this package?

**Comment by GrahamCampbell** [comment]
No, since laravel officially does not support phpunit 6.

**Comment by vinkla** [comment]
Too bad, PHPUnit 6.0 is much faster.

**Comment by vinkla** [comment]
When do you plan to drop PHP 5.5?

**Comment by GrahamCampbell** [comment]
I will go straight from php 5.5 to 7.0, to align with the laravel 5.5 release. Support for older versions of laravel and phpunit will remain in the current release series.
