### ISSUE TITLE
Laravel 5.5 Orchestra Testbench Issue

### ISSUE THREAD

**Issue by vinkla** [GrahamCampbell/Laravel-TestBench#18]
When requiring this package in a Laravel package which only supports version 5.5 it still installs an older version of `orchestra/testbench`. 

I've provided a failed job from Travis:
https://travis-ci.org/vinkla/laravel-algolia/jobs/271252437

If I specify the exact version of  `orchestra/testbench` in my package it works fine. Though, it shouldn't be necessary right?

**Comment by GrahamCampbell** [comment]
D'no. Probably a composer issue?

**Comment by vinkla** [comment]
> D'no. Probably a composer issue?

Maybe. D'no.

**Comment by GrahamCampbell** [comment]
If you are using dependency caching on travis, then that would definitely break things. Composer's cache is rubbish.

**Comment by vinkla** [comment]
Don't think it is Travis, I'm having the same issue locally.

**Comment by GrahamCampbell** [comment]
Yeh, you will have a local cache. Try running `composer clear-cache && rm -rf vendor composer.lock`. Then, try installing again.

**Comment by vinkla** [comment]
Just tried it and I'm still having the same issue 😢;

```
.PHP Fatal error:  Declaration of Illuminate\Container\Container::make($abstract) must be compatible with Illuminate\Contracts\Container\Container::make($abstract, array $parameters = Array) in /Users/vincent/Sites/laravel-facebook/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 13
```

**Comment by GrahamCampbell** [comment]
Looks like composer is installing the wrong versions of laravel and the illuminate packages.

**Comment by GrahamCampbell** [comment]
Not really anything I can do on this repo to fix that I'm afraid.

**Comment by vinkla** [comment]
Oh, are you having the same issue as well? Should be notify them?

**Comment by GrahamCampbell** [comment]
I've not seen this issue before.
