### ISSUE TITLE
Migrate PHPUnit configuration to 10.0

### ISSUE THREAD

**Issue by jnoordsij** [GrahamCampbell/Laravel-TestBench#32]
While running tests for #31, I noticed a warning from PHPUnit:

```
There was 1 PHPUnit warning:

1) Your XML configuration validates against a deprecated schema. Migrate your XML configuration using "--migrate-configuration"!
```

This probably needs to be addressed at some point; I'm not sure if the new schema is compatible with older versions.

**Comment by GrahamCampbell** [comment]
v6.0.0 will be released today with PHPUnit 10, Laravel 10, and PHP 8.2 support.
